- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required and purge their configuration files
  apt:
    autoremove: yes
    purge: true

- name: Disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication yes"
    line: "PasswordAuthentication no"
    state: present
    backup: yes
    validate: /usr/sbin/sshd -T -f %s
  notify: Restart ssh

- name: Enable passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
    state: present
