- name: Update packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: yes
    purge: true

- name: Install pip
  ansible.builtin.command:
    cmd: python -m ensurepip
  args:
    creates: /usr/bin/pip3
  become: true

- name: Upgrade pip to latest version
  ansible.builtin.command:
    cmd: python3 -m pip install --upgrade pip
  become: true
