---
- name: Disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication yes"
    line: "PasswordAuthentication no"
    state: present
    backup: yes
    validate: /usr/sbin/sshd -T -f %s
  notify: Restart SSH daemon
